using DrawnUi.Draw;
using OpenTK.Windowing.GraphicsLibraryFramework;

namespace DrawnUi.OpenTk;

public static class OpenTkKeyMapper
{
    public static InputKey? Map(Keys key) => key switch
    {
        Keys.Left => InputKey.ArrowLeft,
        Keys.Right => InputKey.ArrowRight,
        Keys.Up => InputKey.ArrowUp,
        Keys.Down => InputKey.ArrowDown,
        Keys.Space => InputKey.Space,
        Keys.Enter => InputKey.Enter,
        Keys.KeyPadEnter => InputKey.Enter,
        Keys.Escape => InputKey.Escape,
        Keys.Backspace => InputKey.Backspace,
        Keys.Tab => InputKey.Tab,
        Keys.Delete => InputKey.Delete,
        Keys.Home => InputKey.Home,
        Keys.End => InputKey.End,
        Keys.PageUp => InputKey.PageUp,
        Keys.PageDown => InputKey.PageDown,
        Keys.LeftShift => InputKey.ShiftLeft,
        Keys.RightShift => InputKey.ShiftRight,
        Keys.LeftControl => InputKey.ControlLeft,
        Keys.RightControl => InputKey.ControlRight,
        Keys.LeftAlt => InputKey.AltLeft,
        Keys.RightAlt => InputKey.AltRight,
        Keys.A => InputKey.KeyA,
        Keys.B => InputKey.KeyB,
        Keys.C => InputKey.KeyC,
        Keys.D => InputKey.KeyD,
        Keys.E => InputKey.KeyE,
        Keys.F => InputKey.KeyF,
        Keys.G => InputKey.KeyG,
        Keys.H => InputKey.KeyH,
        Keys.I => InputKey.KeyI,
        Keys.J => InputKey.KeyJ,
        Keys.K => InputKey.KeyK,
        Keys.L => InputKey.KeyL,
        Keys.M => InputKey.KeyM,
        Keys.N => InputKey.KeyN,
        Keys.O => InputKey.KeyO,
        Keys.P => InputKey.KeyP,
        Keys.Q => InputKey.KeyQ,
        Keys.R => InputKey.KeyR,
        Keys.S => InputKey.KeyS,
        Keys.T => InputKey.KeyT,
        Keys.U => InputKey.KeyU,
        Keys.V => InputKey.KeyV,
        Keys.W => InputKey.KeyW,
        Keys.X => InputKey.KeyX,
        Keys.Y => InputKey.KeyY,
        Keys.Z => InputKey.KeyZ,
        Keys.D0 => InputKey.Digit0,
        Keys.D1 => InputKey.Digit1,
        Keys.D2 => InputKey.Digit2,
        Keys.D3 => InputKey.Digit3,
        Keys.D4 => InputKey.Digit4,
        Keys.D5 => InputKey.Digit5,
        Keys.D6 => InputKey.Digit6,
        Keys.D7 => InputKey.Digit7,
        Keys.D8 => InputKey.Digit8,
        Keys.D9 => InputKey.Digit9,
        Keys.F1 => InputKey.F1,
        Keys.F2 => InputKey.F2,
        Keys.F3 => InputKey.F3,
        Keys.F4 => InputKey.F4,
        Keys.F5 => InputKey.F5,
        Keys.F6 => InputKey.F6,
        Keys.F7 => InputKey.F7,
        Keys.F8 => InputKey.F8,
        Keys.F9 => InputKey.F9,
        Keys.F10 => InputKey.F10,
        Keys.F11 => InputKey.F11,
        Keys.F12 => InputKey.F12,
        _ => null
    };
}
